version: '3'
services:
  database:
    image: 'postgres:latest'
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: mealplanner
      POSTGRES_PASSWORD: mealplanner
      POSTGRES_DB: mealplanner
